rootProject.name = "tveebot"
include("app")
include("app-api")
include("downloader-api")
include("downloader-lib")
include("tracker-api")
include("tracker-lib")
include("library-api")
include("library-lib")
include("rss-feed")
